### ISSUE TITLE
Pseudo-selector without & isn't properly namespaced

### ISSUE THREAD

**Issue by TrevorBurnham** [TrevorBurnham/babel-plugin-namespace-styled-components#4]
Test case that came up today:

```css
font: inherit;
::before {
  content: "${pseudoContent}";
}
```

Currently, the pseudo-selector is lost. Putting an `&` in front of the `::before` is sufficient to make it get namespaced, but shouldn't be required.
